R2s example add outputs
pyne/pyne pull request #1085
Opened 2019-01-08 20:54 UTC by zxkjack123

Update the R2S userguide according to the updated r2s example files: https://github.com/pyne/data/pull/17. 

- Geometry of the r2s example is changed
- Some folder names are changed

2019-01-09 16:25 UTC, gonuke requested changes
A few language improvements.

You might want to update the tense from "could be" to "can be" throughout...

2019-01-09 16:25 UTC, gonuke commented on docs/usersguide/r2s.rst
> +.. figure:: r2s_example_geometry.pdf
I think this probably needs to be a `png` and not a `pdf` to render properly...

2019-01-09 16:25 UTC, gonuke commented on docs/usersguide/r2s.rst
> +The example geometry composed of four cubes of size 10x10x10 cm3. It comsists of two different material, the water (in blue) and the steel (in red). The upper left cube (in white) is void.
consists
```suggestion
The example geometry is composed of four cubes of size 10x10x10 cm3. It consists of two different materials, the water (in blue) and the steel (in red). The upper left cube (in white) is void.
```

2019-01-09 16:25 UTC, gonuke commented on docs/usersguide/r2s.rst
> +Using a simple geometry as a example, here is how we perform (voxel) R2S calculation.
should we introduce the concept of voxel vs. sub-voxel before describing "voxel" R2s?

2019-01-09 16:25 UTC, gonuke commented on docs/usersguide/r2s.rst
> +There is a isotropic single energy (14 MeV) neutron point source in the center of the bottom right cube.
```suggestion
There is an isotropic monoenergetic (14 MeV) neutron point source in the center of the bottom right cube.
```

2019-01-09 16:25 UTC, gonuke commented on docs/usersguide/r2s.rst
> +The following content demonstrates the process of caculate the shutdown dose rate of this model at the time of 1 hour after shutdown.
```suggestion
The following content demonstrates the process of caculating the shutdown dose rate of this model at the time of 1 hour after shutdown.
```

2019-01-09 16:25 UTC, gonuke commented on docs/usersguide/r2s.rst
> +Build the model using trelis and set material group and export to `geom_without_material.h5m`.
```suggestion
Build the model using Trelis (TM) and set material group and export to `geom_without_material.h5m`.
```
We may also want to add a link to Trelis and/or the DAGMC documentation

2019-01-09 16:25 UTC, gonuke commented on docs/usersguide/r2s.rst
> +Examples could be seen 'alara_params_example.txt' and 'config_example.ini' in 'r2s_examples/r2s_run'.
```suggestion
Examples can be seen in 'alara_params_example.txt' and 'config_example.ini' in 'r2s_examples/r2s_run'.
```

2019-01-09 16:25 UTC, gonuke commented on docs/usersguide/r2s.rst
> +`ALARA/data <`r2s_examples <https://github.com/svalinn/ALARA/tree/master/data.>`_.
this seems to have too many back ticks (`)?

2019-01-09 17:33 UTC, zxkjack123 commented on docs/usersguide/r2s.rst
> +`ALARA/data <`r2s_examples <https://github.com/svalinn/ALARA/tree/master/data.>`_.
That's true. It has been updated now.

2019-01-09 17:34 UTC, zxkjack123 commented
@gonuke Made some changes to the sentences and the figures.

2019-01-16 22:12 UTC, gonuke commented on docs/usersguide/r2s.rst
> +The example geometry is composed of four cubes of size 10x10x10 cm3. It consists of two different materials, the water (in blue) and the steel (in red). The upper left cube (in white) is void.
```suggestion
The example geometry is composed of four cubes of size 10x10x10 cm\ :sup:`3`\ . It consists of two different materials, the water (in blue) and the steel (in red). The upper left cube (in white) is void.
```

2019-01-17 05:14 UTC, gonuke approved these changes

2019-01-17 05:14 UTC, gonuke commented
Thanks @zxkjack123

2019-01-17 05:14 UTC, merged