MCNP precision
pyne/pyne pull request #1204
Opened 2019-12-19 22:40 UTC by gonuke

Fixes #1203 

Changes the precision reported in the MCNP comment to have 5 decimal places.

2019-12-19 22:43 UTC, bam241 commented
I was doing it, got caught up in meetings... tests need to be fixed as well...
CI did not run there, weird...

2019-12-19 22:58 UTC, bam241 requested changes
Just a minor correction, 
thx @gonuke

2019-12-19 22:58 UTC, bam241 commented on news/mcnp_precision.rst
> +**Changed:** None
```suggestion
**Changed:**
```

2019-12-20 06:38 UTC, zxkjack123 approved these changes
LGTM.

2019-12-20 14:36 UTC, bam241 approved these changes
thx @gonuke 

merging now !

2019-12-20 14:36 UTC, merged