Bug class Xsdir(object): def read corrected
pyne/pyne pull request #1205
Opened 2020-01-17 13:11 UTC by Radiation-Transport

The parsing of XSDIR file was uncorrected when the ZAID XS was defined in more than one row. Indeed, the "+" word was not removed from the list having for instance "+" instead of "p-table" value as in the example reported hereinafter.

	18038.80c 37.6366 xdata/endf71x/Ar/18038.710nc 0 1 4 15536 0 0 2.5301E-08 +
          ptable

2020-01-17 14:51 UTC, pshriwise requested changes
Seems reasonable to me! Thanks for addressing this, @Radiation-Transport.

Just one small line change requested and to satisfy the PR requirements we'll want to add a news file here it seems.

@gonuke do you think an additional test case is in order here? I could take it or leave it.

2020-01-17 14:51 UTC, pshriwise commented on pyne/mcnp.py
> +                words = words[:-1] + extraWords  # Correct bug in the XSDIR parsing
```suggestion
                words = words[:-1] + extraWords
```

2020-01-17 19:23 UTC, gonuke requested changes
Thanks for finding this long-standing bug!

I do think it would be useful to have a test for this, ideally by adding lines with these characteristics in the `dummy_xsdir` files and adding a test to `test_mcnp.py` to ensure it is handled correctly.

Please also note that we require a brief news file to document the change based on `news/TEMPLATE.rst` to facilitate building change logs.

2020-01-25 04:59 UTC, pshriwise commented
@Radiation-Transport I opened a PR into your branch with the addition to our `test_mcnp` file that I think @gonuke was asking for. Once we get that change merged into your branch and take care of that small requested change above I think we'll be good to go.

2020-08-17 01:24 UTC, gonuke commented
@Radiation-Transport - we'd like to include this in an impending release.  Are you able to incorporate the requested changes, or should we take over the PR?

2020-08-17 04:39 UTC, Radiation-Transport commented
Dears,

Please go ahead as we would not like to be a bottleneck in your process,

Thanks for asking.

Cheers,
Marco

From: Paul Wilson <notifications@github.com>
Sent: Monday, 17 August 2020 03:25
To: pyne/pyne <pyne@noreply.github.com>
Cc: Fabbri Marco (F4E) <Marco.Fabbri@f4e.europa.eu>; Mention <mention@noreply.github.com>
Subject: Re: [pyne/pyne] Bug class Xsdir(object): def read corrected (#1205)


@Radiation-Transport<https://github.com/Radiation-Transport> - we'd like to include this in an impending release. Are you able to incorporate the requested changes, or should we take over the PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/pyne/pyne/pull/1205#issuecomment-674610278>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALQVAMLHWX4BTBAIQDHXLD3SBCBFZANCNFSM4KIIC5UQ>.

2020-08-17 15:12 UTC, gonuke commented
Thanks @Radiation-Transport - we'll do it in a way that preserves attribution of your valuable contribution.

2020-08-17 15:15 UTC, gonuke commented
This has been replaced by #1314 to wrap it up with contributions from @Radiation-Transport and @pshriwise

2020-08-17 15:15 UTC, closed without merging