move join_to_string declaration in the header
pyne/pyne pull request #1327
Opened 2020-08-28 20:18 UTC by bam241

Clang didn't like to the way the declaration of `join_to_string` was...

Moving everything int header fixed it....

this is required to amalgamated PyNE and compile it with `clang`. see svalinn/DAGMC#700

2020-08-28 20:45 UTC, pshriwise requested changes
Very small style change, but then I think this good to go.

2020-08-28 20:45 UTC, pshriwise commented on src/utils.h
> +                                  std::string delimiter);
```suggestion
  template std::string join_to_string(std::vector<double> vect,
                                                        std::string delimiter);
```

2020-08-29 01:54 UTC, gonuke approved these changes
Seems OK to me, but I wish I understood why....

2020-08-29 01:55 UTC, gonuke commented
Thanks @bam241

2020-08-29 01:55 UTC, merged

2020-08-29 03:42 UTC, bam241 commented
@gonuke

I did not read it yet, but here is what @pshriwise told me on slack:
```
This has a pretty good explanation of why it's best to put templates in the header file. http://www.cs.technion.ac.il/users/yechiel/c++-faq/templates-defn-vs-decl.html

I think gcc is smart enough to add that template definition to the header file's translation unit (as if it were an inline'd function) but clang apparently isn't
```