Fixes for nuc_data_make to work from scratch
pyne/pyne pull request #1333
Opened 2020-09-10 12:56 UTC by gonuke

This set of changes is intended to allow `nuc_data_make` to function correctly when working from scratch rather than from the prebuilt data.

* Changes to KAERI data:
   * different download location for zip fiel
   * don't try to download missing data from KAERI, it's no longer available
   * missing data are just super-heavy elements, anyway

* Changes to writing material library for new interface

2021-03-27 16:46 UTC, gonuke commented
This can transition from draft after pyne/data #24 is merged.

2021-06-24 16:15 UTC, bam241 commented
pyne/data#24 has been merged. I think this can be turn into a full PR...

2021-07-22 17:07 UTC, bam241 commented
ping @gonuke

2024-02-16 16:11 UTC, ahnaf-tahmid-chowdhury commented
@gonuke, please resolve the conflicts and then we may give this a try.

2024-02-17 03:52 UTC, ahnaf-tahmid-chowdhury commented on CHANGELOG.rst
> +      * update material_library writing interface
Please move this under next Version section.

2024-02-17 04:06 UTC, ahnaf-tahmid-chowdhury requested changes
Thanks @gonuke, I have a few suggestions.

2024-02-17 04:06 UTC, ahnaf-tahmid-chowdhury commented on pyne/dbgen/simple_xs.py
> +                                                                          htmlfile))
I think we can remove not from the if condition, thus we can also remove pass and else conditions.
```suggestion
        if htmlfile in already_grabbed:
            all_nuclides = all_nuclides | parse_for_all_isotopes(os.path.join(build_dir, 
                                                                          htmlfile))
```

2024-02-17 04:06 UTC, ahnaf-tahmid-chowdhury commented on pyne/dbgen/simple_xs.py
> +    zip_url = 'http://raw.githubusercontent.com/pyne/data/master/kaeri.zip'
Can we use HTTPS for secure connection?
```suggestion
    zip_url = 'https://raw.githubusercontent.com/pyne/data/master/kaeri.zip'
```

2024-02-19 04:56 UTC, ahnaf-tahmid-chowdhury requested changes

2024-02-19 04:56 UTC, ahnaf-tahmid-chowdhury commented on CHANGELOG.rst
> +      * update material_library writing interface
@gonuke, maybe you have forgotten to resolve this?

2024-02-20 03:44 UTC, ahnaf-tahmid-chowdhury approved these changes
Thanks, @gonuke!

2024-02-20 03:45 UTC, merged