fixes for Windows cpp17
pyne/pyne pull request #1390
Opened 2021-06-30 17:03 UTC by bam241

filesystem::canonical() needs to be converted to char* ...

2021-06-30 17:04 UTC, bam241 commented
`const char* full_filepath = std::filesystem::canonical(filename.c_str()).string().c_str();` could have been directly casted as a string:
`string full_filepath = std::filesystem::canonical(filename.c_str()).string();`
but I kept it that way for consistency, but can change it if anyone feels strongly about this...

2021-07-02 16:32 UTC, gonuke requested changes
I thought I had already submitted this review (my iPad app is throwing me off)...

and now I see that you already recognized the same thing.  I think it makes sense to define `full_filepath` as a `std::string` in both instances.  The results of `realpath` will be promoted to the `std::string` on assignment.

2021-07-02 16:32 UTC, gonuke commented on src/utils.cpp
> +  const char* full_filepath = std::filesystem::canonical(filename.c_str()).string().c_str();
We are about to recast this as a `std::string`.  Can't we just make `full_filepath` be `std::string` and avoid the conversion to `char*`?

2021-07-02 16:48 UTC, bam241 commented on src/utils.cpp
> +  const char* full_filepath = std::filesystem::canonical(filename.c_str()).string().c_str();
yes that's what I was suggesting. I kept it that way so no windows and windows have the same kind of behavior and the temp variable has the same type...

2021-07-02 17:41 UTC, gonuke approved these changes
LGTM - thanks @bam241

2021-07-02 17:42 UTC, merged