Improving ability to invoke PyNE Version CMake macro when submodule
pyne/pyne pull request #1431
Opened 2021-11-11 14:18 UTC by gonuke

## Description
Introduce features and variables that allow the PyNE Version CMake macro to be called from a different path location

## Motivation and Context
The PyNE Version macro works for build from within PyNE, but needs more support when PyNE is a submodule in a different path.

## Changes
This can be considered a feature enhancement with changes in the PyNE Version macro.

2021-11-12 17:57 UTC, gonuke commented
I think this has all the features necessary to allow DAGMC get the version updated successfully before building

2021-11-12 18:00 UTC, gonuke commented
see here for tests of a version of DAGMC using this hash of pyne: https://github.com/gonuke/DAGMC/runs/4192945393?check_suite_focus=true

2021-11-12 18:05 UTC, gonuke commented
Once this is merged, I'll update the DAGMC PR to refer to the merged hash

2021-11-12 18:25 UTC, gonuke commented
Needed another DAGMC update, so hopefully passing tests will be here: https://github.com/gonuke/DAGMC/actions/runs/1454268099

2021-11-12 18:58 UTC, gonuke commented
I've added Mac and Windows testing, available here: https://github.com/gonuke/DAGMC/actions

2021-11-12 19:57 UTC, shimwell commented
> Needed another DAGMC update, so hopefully passing tests will be here: https://github.com/gonuke/DAGMC/actions/runs/1454268099

All 12 passed :tada:

2021-11-12 19:57 UTC, shimwell commented
> I've added Mac and Windows testing, available here: https://github.com/gonuke/DAGMC/actions

all 3 passed :tada:

2021-11-12 19:58 UTC, shimwell approved these changes

2021-11-13 18:41 UTC, pshriwise requested changes
Tried this out and it works quite well! No line comments from me. The only thing I'll request is updates to the docs (maybe near info on amalgamation) to indicate how to use PyNE as a submodule in another project.

2021-11-13 21:12 UTC, gonuke commented
> Tried this out and it works quite well! No line comments from me. The only thing I'll request is updates to the docs (maybe near info on amalgamation) to indicate how to use PyNE as a submodule in another project.

Yeah.... so this raises an additional question about ensuring the version substitution happens prior to amalgamation.  At the moment, that solution lives in DAGMC.  I can document how to invoke the version  substitution from a code that includes PyNE as a submodule, but DAGMC then also has a custom amalgamation script, etc...  I think we need a slightly better solution that lives in PyNE before we can document it well.

2021-11-13 23:20 UTC, pshriwise commented
Hrmm so you're suggesting we perhaps move the new amalgamation script from DAGMC to PyNE?

2021-11-14 00:03 UTC, gonuke commented
No - that won't quite do it, either.

In DAGMC, I call a CMake macro for version substitution (because we're already in the middle of a CMake build), and then we call a bash script that ultimately calls the normal amalgamate script.

Since we are relying on CMake-based version substitution, we need to somehow invoke CMake at the beginning of the amalgamate process.  It might be about making a separate CMakeList config file for amalgamation that invokes the same macro?

2021-11-14 00:04 UTC, gonuke commented
But I'm not sure we can invoke that from within the amalgamation python script, because we call that from DAGMC's CMake build and that might just mess things up.... although it's invoked from within a new bash shell (too many layers!)

2021-11-16 06:33 UTC, pshriwise commented
Not very pretty, but we could make it an option to run the CMake preprocessing in the amalgamation script? Standard use would execute the CMake substitution, but we'd tell it not to in DAMGC b/c we handle that with the `PYNE_SUBMODULE_PATH` variable?

I'm wondering if we, unfortunately, approached this the wrong way and maybe should have stored the version information in the Python side and generated a `pyne_version.h` file using Python instead?

2021-11-16 13:08 UTC, gonuke commented
I think this was right because we probably will ultimately want to have CMake put this info in other places (see current issue with MOAB...)

2021-11-16 13:12 UTC, gonuke commented
If we did it in the amalgamation script, we could back out changes in DAGMC and get rid of the SUBMODULE_PATH stuff?

2022-02-07 20:03 UTC, gonuke commented
withdrawing this in favor of #1434

2022-02-07 20:03 UTC, closed without merging