fix mcnp6 version check for serial
pyne/pyne pull request #1454
Opened 2022-06-07 12:43 UTC by zxkjack123

## Description
A small fix for Ptrac version check.

## Behavior
The code may fail below when the Ptrac is generated with the serial mcnp6:
https://github.com/pyne/pyne/blob/800c75a6099f81ac73460166aea936dea4835f00/pyne/mcnp.py#L1233-L1234

This PR fixes this problem.

2022-06-23 12:47 UTC, gonuke requested changes
Thanks for this update.  I wonder why we didn't find it before!

I have suggested a slightly different approach that may be more robust.

2022-06-23 12:47 UTC, gonuke commented on pyne/mcnp.py
>              mcnp_version = self.mcnp_version_info[8:13]
Is it more robust to `strip()` the whitespace from the end of this?
```suggestion
            mcnp_version = self.mcnp_version_info[8:13].strip()
```

2024-02-16 15:48 UTC, ahnaf-tahmid-chowdhury commented on pyne/mcnp.py
>              mcnp_version = self.mcnp_version_info[8:13]
Sure, but I like @zxkjack123 to make the change and what he thinks.

2024-10-29 05:24 UTC, ahnaf-tahmid-chowdhury commented
The file `mcnp6_serial_ptrac_i4_little.ptrac` is a binary file. I think we need to verify that `self.endianness` in PtracReader matches the actual file’s endianness. Also, We should consider adding a try-except block to catch and log the values of `length` and `length2` when they don't match for better output.

2024-10-30 01:23 UTC, zxkjack123 commented
@gonuke @ahnaf-tahmid-chowdhury I forgot this PR for a long time. I made a new repo with the same changes to a new PR #1558 to avoid the rebase conflicts fixing. Please move to the #1558 for further discussion.

2024-10-31 01:31 UTC, gonuke commented
Please feel free to close this now that #1558 is merged, @zxkjack123

2024-11-01 15:45 UTC, zxkjack123 commented
Close this PR as #1558 merged.

2024-11-01 15:45 UTC, closed without merging