Add missing rxname offsets
pyne/pyne pull request #1482
Opened 2023-06-06 19:23 UTC by kevin-servaenergy

Please follow these guidelines when making a Pull Request.
This template was adapted from [here](https://github.com/stevemao/github-issue-templates/blob/master/questions-answers/PULL_REQUEST_TEMPLATE.md) and [here](https://github.com/stevemao/github-issue-templates/blob/master/conversational/PULL_REQUEST_TEMPLATE.md).

## Description
Add missing rxname offsets to map.

--Please verify the offsets. I am simply a developer and nuclear is not my field...

## Motivation and Context
When parsing ENDFBVIII (https://www.nndc.bnl.gov/endf-b8.0/zips/ENDF-B-VIII.0.zip) I get a RuntimeError when using functions rxname.parent and rxname.child from python.

## Changes
What kind of change does this PR introduce? (Bug fix, feature, documentation update...)
Bug fix

## Behavior
What is the current behavior? What is the new behavior?
RuntimeError when calling from python with certain rx ids. New behavior is that the functions return a nuc id.

## Other Information
Other relevant information to this pull request.

## Changelog file
All pull requests are required to update the [CHANGELOG](https://github.com/pyne/pyne/blob/develop/CHANGELOG.rst) file with the PR.  Your update can take different forms including:

* creating a new entry describing your change, including a reference to this pull request number
* adding a reference to your pull request number to an exist entry if that entry can include your changes

2023-06-15 23:14 UTC, gonuke requested changes
Thanks for these additions @kevin-servaenergy.  The math all looks right to me.

Oddly, though, this seems to be passing a test that it shouldn't.  I don't think that's your fault, but please add an entry to the `CHANGELOG.rst` with a line that describes the change.

2023-06-27 22:50 UTC, kevin-servaenergy commented
@gonuke Sure thing. Added to changelog.

2023-06-28 18:00 UTC, gonuke approved these changes

2023-06-28 18:04 UTC, gonuke commented
Thanks @kevin-servaenergy

2023-06-28 18:04 UTC, merged