Review Tutorials and Bug Fixes
pyne/pyne pull request #1486
Opened 2023-06-29 16:56 UTC by ahnaf-tahmid-chowdhury

## Description
This Pull Request updates the documentation and includes bug fixes for the following notebooks:
- 00-intro.ipynb
- 01-nuclide-naming.ipynb
- 02-materials.ipynb
- 04-reaction_names.ipynb
- 05-cross-sections.ipynb
- 06-transmutation.ipynb
- 07-mesh-basics.ipynb
- 10-spatial-solver.ipynb

## Motivation and Context
The motivation behind this PR is to improve the documentation and address some bugs in the mentioned notebooks. The changes made to provide more context and enhance the overall user experience.

## Changes
- Added more context and information to the documentation in the mentioned notebooks.
- Fixed a bug in SlicePlot that was causing an attribute error ('_dst_group_struct').
- Skipped notebook 03-nuclear-data.ipynb due to a recurring issue with the 'map(nucname.anum, NuclearName)' function.
- Skipped notebook 08-diffusion.ipynb as it is outdated and incompatible with Python 3.
- Skipped notebook 11-ensdf-processing.ipynb due to an outdated link format.

## Behavior
The current behavior of the notebooks is either incomplete or contains errors. This PR aims to address these issues by improving the documentation and fixing the bug in SlicePlot.

## Changelog file
- Updated the CHANGELOG file to include a new entry describing the changes made in this Pull Request and referenced this PR number.

2023-07-19 13:34 UTC, gonuke commented
FYI, @ahnaf-tahmid-chowdhury - I am working through these modifications to review.  It's challenging to review the Jupyter Notebooks, but I am making progress.

2023-07-19 15:15 UTC, gonuke requested changes
Thanks so much for this thorough review @ahnaf-tahmid-chowdhury !!!  I've noted a few very minor things, in the spirit of your thoroughness!

2023-07-19 15:15 UTC, gonuke commented on tutorial/00-intro.ipynb
> +    "As a **user**, utilizing PyNE for your work or research eliminates the need for you to create and upkeep similar functionality in your own software. By using PyNE, you can save time and effort i
```suggestion
    "As a **user**, using PyNE for your work or research eliminates the need for you to create and upkeep similar functionality in your own software. By using PyNE, you can save time and effort in developing and maintaining those features.\n",
```

2023-07-19 15:15 UTC, gonuke commented on tutorial/02-materials.ipynb
> +    "`Material` may be initialized in a number of different ways.  For example, initializing from\n",
```suggestion
    "A `Material` may be initialized in a number of different ways.  For example, initializing from\n",
```

2023-07-19 15:15 UTC, gonuke commented on tutorial/02-materials.ipynb
> +    "When creating a new instance of the Material class, the mass fractions that define it are already normalized. However, you can retrieve the unnormalized mass vector using the ``Material.mult_by_
```suggestion
    "When creating a new instance of the `Material` class, the mass fractions that define it are already normalized. However, you can retrieve the unnormalized mass vector using the ``Material.mult_by_mass()`` method. If you need to normalize the mass or composition, you can use the provided normalization routines: ``Material.normalize()`` or ``Material.norm_comp()``.\n",
```

2023-07-19 15:15 UTC, gonuke commented on tutorial/02-materials.ipynb
> +    "For example, let's consider a scenario where we have 42 units of Low-Enriched Uranium (LEU), consisting of 1.68 units of U-235 and 40.32 units of U-238."
```suggestion
    "For example, let's consider a scenario where we have 42 units of low-enriched uranium (LEU), consisting of 1.68 units of U-235 and 40.32 units of U-238."
```

2023-07-19 15:15 UTC, gonuke commented on tutorial/02-materials.ipynb
> +    "Furthermore, it is also possible to create a new material from atom fractions using other materials as references. This scenario often occurs in reactors, where the fuel vector is combined withi
```suggestion
    "Furthermore, it is also possible to create a new material from atom fractions using other materials as references. This scenario often occurs in reactors, where the fuel vector is combined within another chemical form. Here is an example of obtaining a uranium oxide material by specifying the atom fractions of oxygen and low-enriched uranium:"
```

2023-07-19 15:15 UTC, gonuke commented on tutorial/05-cross-sections.ipynb
> +    "xscache['H1', 'gamma']"
I'm wondering if the point of this example was to demonstrate that if you ask for a cross-section that is not in the cache (or doesn't exist) it will just return 0?  I don't think this is a typo???

2023-07-19 15:41 UTC, ahnaf-tahmid-chowdhury commented on tutorial/05-cross-sections.ipynb
> +    "xscache['H1', 'gamma']"
In that case, I think we need to mention this in the tutorial. I will introduce an additional line in the tutorial that addresses this point,  to ensure a better user experience.

2023-07-22 04:54 UTC, ahnaf-tahmid-chowdhury commented
Dear, @gonuke. Please let me know if there are any other changes that you would like to add. As mentioned before, I have skipped reviewing `08-diffusion.ipynb` and `11-ensdf-processing.ipynb` for now. We will need to work with the raw code extensively, as they appear to be very old and written for Python 2. I have also noticed that `itaps` is not available in Python 3. Therefore, I am thinking of creating another pull request to address these issues separately.

For the current pull request, I believe it is ready to be merged. If you would like more time or further discussion, I can convert it to a draft.

2023-07-22 11:32 UTC, gonuke commented
Thanks @ahnaf-tahmid-chowdhury for this contribution!

2023-07-22 11:32 UTC, merged

2023-07-25 18:09 UTC, ahnaf-tahmid-chowdhury commented
This PR solved the issue #1037

2023-07-25 18:15 UTC, ahnaf-tahmid-chowdhury commented
This PR solved the issue #1300