Update run conditions for workflows
pyne/pyne pull request #1494
Opened 2023-07-25 23:19 UTC by bquan0

## Description
Makes `build_test.yml` run when it or the composite action it uses is updated. Also makes `install_script.yml` run on every `push` to `develop` and every `pull_request` to develop. 

## Motivation and Context
Closes #1292 and #1491, which request the two features I mentioned above. 

## Behavior
The previous behavior was that `build_test.yml` ran even though there were no changes to itself or the dockerfile that built the image it tested. This is because it used `paths-ignore:` to filter out files instead of using `paths:` to specify files to check if they have been changed. Also, it used to run on every `push:` to `develop`, which is a condition that has now been removed. 
The previous behavior of `install_script.yml` was that it only ran when it or the install script `ubuntu.sh` was changed. The current behavior is that it now also runs whenever there is a `push` or `pull` to `develop`. 

## Other Information
One thing I was wondering was if I should add `docker/*` to the `paths:` of `build_test.yml` since it's also in `docker_publish.yml`. I didn't add it because I thought it would be redundant since `docker_publish.yml` has `docker/*` in its `paths:` and `docker_publish.yml` has a job which runs the same job found in `build_test.yml`. 

## Changelog file
All pull requests are required to update the [CHANGELOG](https://github.com/pyne/pyne/blob/develop/CHANGELOG.rst) file with the PR.  Your update can take different forms including:

* creating a new entry describing your change, including a reference to this pull request number
* adding a reference to your pull request number to an exist entry if that entry can include your changes

2023-07-26 07:51 UTC, gonuke requested changes
unless I misunderstand the `paths` scope, I think we want this to run more often than indicated here.

2023-07-26 07:51 UTC, gonuke commented on .github/workflows/build_test.yml
> +      - '.github/actions/build-test/action.yml'
This says it will only run if these files change, but we want testing to run for any file changes

2023-07-26 07:51 UTC, gonuke commented on .github/workflows/install_script.yml
>        - '.github/workflows/install_script.yml'
I think we want this to run for all file changes

2023-07-27 01:08 UTC, bquan0 commented
Right, I now see that I misinterpreted the issue for `install_script.yml`. However, on the issue about `build_test.yml`, it says that the workflow shouldn't run if there are only documentation changes.

2023-07-27 23:19 UTC, gonuke commented
Fair enough, we can add a path exclusion for documentation on the `build_test.yml`

2023-07-28 03:16 UTC, bquan0 commented
Just added a list of files to `paths_ignore:` for `build_test.yml`. Let me know if there are any changes I should make to the list!

2023-07-28 06:26 UTC, gonuke commented
Maybe we need to revisit/talk through all the circumstances we use to run all of these at a future software meeting.

2023-08-05 18:25 UTC, gonuke commented
I think we need to restrict the `cython` installation to be <3.0.  This is a new change based on which `cython` version is automatically being installed.

2023-08-05 18:28 UTC, gonuke commented
I encountered this in DAGMC recently and didn't port it over to here.  May also require an update to the install script.

2023-08-05 21:12 UTC, bquan0 commented
Right now, the `build_test.yml` workflow is running on my fork, but it runs into errors because the docker image it tries to access if from `pyne`. Should I add a run condition that restricts it to only run when the owner of the repo is `pyne`?
After trying out a bunch of variations for installing `cython` but restricting its version to be <3.0, I found that `pip install cython==0.*` was the syntax that works (since the versions before 3.0 are numbered starting with 0.). I'm not sure why `pip install cython<3.0` doesn't work, however. This is the [working run](https://github.com/bquan0/pyne/actions/runs/5772735502/job/15648016783).

2023-08-05 23:10 UTC, gonuke commented
I think you need `'cython<3'` with quotation marks since the less than symbol has a special meaning on the command line

2023-08-06 00:30 UTC, bquan0 commented
Ah, makes sense. Looks like that syntax is [working now](https://github.com/bquan0/pyne/actions/runs/5773523104)!

2023-08-06 14:03 UTC, gonuke commented
Thanks @bquan0 - I think this looks ready to merge - let's try...

2023-08-06 14:03 UTC, gonuke approved these changes

2023-08-06 14:03 UTC, merged