Move from `#define isnan` to `std::isnan`.
pyne/pyne pull request #1502
Opened 2023-09-11 20:48 UTC by pshriwise

## Description

Resolves #1501.

Fixes a problem with the preprocessor macro in `utils.h` breaking usage of `std::isnan` in other packages b/c it is in the global namespace. 

## Motivation and Context
This was noted first [here](https://github.com/pyne/pyne/pull/836 ). And causes a problem when compiling DAGMC with recent versions of MOAB as noted here #1501.

## Changes
After conferring with @gonuke, the determined solution was to replace the `isnan` implementation selected by PyNE with `std::isnan` in the `.cpp` files where it is used.

It's worth noting that this may break compatibility with versions of GCC older than 4.0 and may break compilations on Windows using visual studio compilers from before 2015. Both sacrifices we were willing to make. 

## Changelog file
All pull requests are required to update the [CHANGELOG](https://github.com/pyne/pyne/blob/develop/CHANGELOG.rst) file with the PR.  Your update can take different forms including:

* creating a new entry describing your change, including a reference to this pull request number
* adding a reference to your pull request number to an exist entry if that entry can include your changes

2023-09-11 21:17 UTC, gonuke requested changes
Found a typo in the changelog (I hate it when this is the only comment...). I'll also do a search for `isnan` separately just to put a 2nd pair of eyes on it

2023-09-11 21:17 UTC, gonuke commented on CHANGELOG.rst
> +   * Replacig '#define isnan' with 'std::isnan' (#1502)
```suggestion
   * Replacing '#define isnan' with 'std::isnan' (#1502)
```

2023-09-11 21:34 UTC, gonuke commented
I've confirmed that there are no dangling instances of `isnan`, but did fine an interesting 10 year old entry in the style guide to always use `std::isnan()`!! :)

2023-09-12 00:52 UTC, pshriwise commented on CHANGELOG.rst
> +   * Replacig '#define isnan' with 'std::isnan' (#1502)
Thanks!!

2023-09-12 08:21 UTC, gonuke commented
Thanks @pshriwise for the quick action

2023-09-12 08:21 UTC, gonuke approved these changes
This looks good to me

2023-09-12 08:21 UTC, merged