Change references of `basestring` to `str`
pyne/pyne pull request #1544
Opened 2024-07-09 15:41 UTC by bennibbelink

## Description
Removes code that was in place to support Python2 and Python3.  The brunt of this PR is changing references to `basestring` to reference `str` instead.

## Motivation and Context
I noticed the prevalence of `basestring` when working on #1543.  It doesn't necessarily fix the issues experienced in that PR, but it just simplifies the codebase a little bit.

## Changes
Deprecation of Python2 support.

2024-07-12 18:04 UTC, bquan0 approved these changes
Looks good to me. Thanks @bennibbelink for these changes!

2024-07-16 01:52 UTC, gonuke requested changes
Identified many places that we can now avoid importing `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/dbgen/cinder.py
> -if sys.version_info[0] > 2:
do we still need to import `sys`?

2024-07-16 01:52 UTC, gonuke commented on pyne/dbgen/kaeri.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/endl.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/ensdf.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/ensdf_processing.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/material.pyx
> -if sys.version_info[0] >= 3:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/material_library.pyx
>              if sys.version_info[0] >= 3 and isinstance(lib, bytes):
I wonder if we need this still either?

2024-07-16 01:52 UTC, gonuke commented on pyne/mesh.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/origen22.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/serpent.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/xs/cache.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/xs/channels.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on pyne/xs/data_source.py
> -if sys.version_info[0] > 2:
no longer need to import `sys`

2024-07-16 01:52 UTC, gonuke commented on tests/test_dagmc.py
> -if sys.version_info[0] < 3:
no longer need to import `sys`

2024-07-17 17:13 UTC, gonuke approved these changes
Thanks @bennibbelink

2024-07-17 17:13 UTC, merged