Remove endftod.f90 and rely on C++ version
pyne/pyne pull request #1554
Opened 2024-09-16 16:45 UTC by ahnaf-tahmid-chowdhury

See #1553

2025-06-26 13:14 UTC, gonuke requested changes
I think we can simplify this further if we are going to make this change.

I'm also a little worried about the need to change the test.

2025-06-26 13:14 UTC, gonuke commented on src/utils.h
> +  extern double (*endftod)(char * s);
If we are getting rid of the different versions, can't we just rename `endftod_cpp` to `endftod` and get rid of the function pointers?

2025-06-26 13:14 UTC, gonuke commented on tests/test_endf.py
> +    assert_allclose(u235.projectile["mass"], 1.0)
I'm concerned about these changes.  I'm definitely curious to see how the `endftod` result is different from the exact test.  I know that there can be floating point issues with exact comparison, but I hoped that conversion from string would not be subject to hose kinds of issues.

2025-06-26 13:14 UTC, gonuke commented on tests/test_endf.py
> -    assert brem.products[0]["za"] == 11  # electrons
This should be an integer comparison and should be exact.  Maybe the issue is that elsewhere in PyNE we need to make sure this is converted from float to integer, since it's probably formatted as a float in ENDF even though it's an integer.

2025-06-26 13:14 UTC, gonuke commented on tests/test_endf.py
> +    assert len(data) >= 17
This change concerns me a little....

2025-06-26 15:30 UTC, ahnaf-tahmid-chowdhury commented on tests/test_endf.py
> +    assert len(data) >= 17
Hmm,interesting to me as well. It failed with Python 3.13. But with 3.10 its working. Maybe it was buffer issue.

2025-06-26 15:31 UTC, ahnaf-tahmid-chowdhury commented on tests/test_endf.py
> -    assert brem.products[0]["za"] == 11  # electrons
I have changed it to 11.0

2025-07-01 02:18 UTC, gonuke approved these changes
Thanks @ahnaf-tahmid-chowdhury

2025-07-01 02:18 UTC, merged