Update docker
pyne/pyne pull request #900
Opened 2017-07-06 04:11 UTC by makeclean

This PR updates the CI build instructions, adds the dockerfile so anyone can rebuild the docker image. In order to test this someone needs to build the docker image, build pyne and run the tests. PR #899 depends upon the changes found in this PR. Once someone approves of these changes I can push the image to dockerhub.

2017-07-06 11:21 UTC, gonuke commented
I'm new to this docker CI stuff...  is there a reason we're not using U16.04?

2017-07-06 12:21 UTC, gonuke requested changes
I'v PR'ed some changed into this branch that match the comments....
Mostly clean up of the MOAB install but also added a DAGMC install

It worked with PR #899

2017-07-06 12:21 UTC, gonuke commented on docker/Dockerfile
> +    mkdir moab && \
don't you need to `cd moab` here?

2017-07-06 12:21 UTC, gonuke commented on docker/Dockerfile
> +    cd .. && \
don't you need to `cd ../..` here?

2017-07-06 12:21 UTC, gonuke commented on docker/Dockerfile
> +    rm -rf bld moab && \
only delete `moab` here (assuming the directory changes I've indicated)

2017-07-06 12:21 UTC, gonuke commented on docker/Dockerfile
> +    git clone https://bitbucket.org/fathomteam/moab && \
perhaps if you clone this repo into a directory called something like `moab-src` it will reduce confusion about which directory you are in.

2017-07-06 12:21 UTC, gonuke commented on docker/Dockerfile
> +    pip install numpy && \
is this because you can't apt-get a new enough version of numpy?

2017-07-06 12:21 UTC, gonuke commented
Is it true that these changes MUST be tested with PR #899?  It seems so to me...

2017-07-21 15:43 UTC, katyhuff commented
Regarding #898, can you update this to python 3?

2017-07-21 16:21 UTC, makeclean commented
I can, but that leaves me with other questions, should python 2.7 also exist alongside, and therefore we test both 2.7 and python 3 compatibility? Or should we only support python3? Which python3, 3.4 3.5? etc.

2017-07-21 16:36 UTC, katyhuff commented
I think the conclusion from the pyne summit was that we should drop python 2 dependency ( @scopatz , @gonuke  can confirm... I left the meeting early). 

If it's reasonable to have many versions of python supported, I'd say do 3.4, 3.5, 3.6, and onward.

2017-08-21 19:20 UTC, makeclean commented
OK, so I have a new docker image with all the python3.5 dependencies met with one exception, PyTAPS - our python interface to MOAB. Now, PyTAPS is as far as I understand orphaned with no further changes to be expected, we also now have a release of MOAB with the pyMOAB interface so future PyNE would probably conform to this interface instead, this is somewhat out of scope to what im doing right now. So as I see it I have 2 options.

1) Continue to try and get beyond the compiling issues I have with PyTAPS and python3, ive already changed the build scripts
2) Ignore testing with PyTAPS and have the CI not built with MOAB (& PyTAPS for meshes) on the understanding that when the new interface is complete someone adds it - PR's that change the mesh interface need therefore to be tested against a different image.

I would be happy to hear opinions

2017-08-30 11:49 UTC, gonuke commented
Don't we need to retain python 2.x support until we replace PyTAPS?  Take PR #901 - it specifically relies on PyTAPS

2017-08-30 11:56 UTC, gonuke reviewed
Still looks like one of your `rm` commands will quietly fail.
Not really a blocking issues since it doesn't affect the success/completion of this.

2017-08-30 11:56 UTC, gonuke commented on docker/DockerFilePyneUbuntu1704Python2
> +    rm -rf bld moab
If this is attempting to delete the `moab` that is the repo, then I think you're in the wrong directory.  
You `cd ..` from `/opt/moab/moab/bld`

2017-08-30 11:56 UTC, gonuke commented on docker/DockerFilePyneUbuntu1704Python3
> +    rm -rf bld moab
similar comment to above about success of removing `moab`

2017-08-30 11:57 UTC, gonuke approved these changes

2017-08-30 21:50 UTC, makeclean commented
Ok so I think this is actually good, but Im seeing failures from CI, one of them is a compilation issue, which I can fix. But the 2 that consistently fail are the index errors from numpy. Could someone please build the current head of develop, ubuntu 16.04 or 17.04 and see if you get failures from nosetests for those two specific tests. Im suspicious that its the numpy/scipy version that I installed into the Docker image

2017-08-31 16:27 UTC, scopatz commented
Hi @makeclean - I am seeing the same issues on develop as I am on your branch and that you are seeing.  So your branch here does no harm.  It is safe to merge in my opinion.

2017-09-01 02:23 UTC, makeclean commented
I'll do one more push to fix the amalgamate build issue, and then address @gonuke's comments then it should be good to go.

2019-03-21 11:39 UTC, gonuke commented
I think this has been superseded by more recent changes.  Are there any features that still aren't included in our CI, @makeclean ?

2020-08-16 17:41 UTC, gonuke commented
Closing this as we have replaced everything here with equivalent capability.

2020-08-16 17:41 UTC, closed without merging